# Generated by Django 5.0.7 on 2024-08-07 09:52

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('acquisition_date', models.DateField()),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('object_url', models.URLField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albapp.batch')),
            ],
            options={
                'db_table': 'image_metadata',
            },
        ),
        migrations.CreateModel(
            name='ShpMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('gps_coords', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('zipcode', models.IntegerField()),
                ('place_name', models.CharField(max_length=100)),
                ('fire_area', models.CharField(max_length=100)),
                ('fire_propagation', models.CharField(max_length=100)),
                ('fire_orientation', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albapp.batch')),
            ],
            options={
                'db_table': 'shp_metadata',
            },
        ),
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('object_url', models.URLField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albapp.batch')),
            ],
            options={
                'db_table': 'video_metadata',
            },
        ),
    ]
